image: Visual Studio 2019
branches:
  only:
    - testing

# Test against the latest version of this Node.js version
environment:
  matrix:
    - nodejs_version: Current
    - nodejs_version: LTS

platform:
  - x64

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version $env:platform
  # install modules
  - npm install --python_include="C:\\\\Python39-x64"

# Post-install test scripts.
#test_script:
  - |-
    SET PATH=C:\\Python39-x64;%PATH%
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - cmd: npm run version
  - cmd: echo %APPVEYOR_BUILD_FOLDER%
  - cmd: npm test

# Don't actually build.
build: off
